//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("iMine Launcher")]
[assembly: System.Reflection.AssemblyDescription("iMine Launcher")]
[assembly: System.Reflection.AssemblyProduct("iMine Launcher")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.9.4.L-040119")]
[assembly: System.Reflection.AssemblyVersion("0.9.4")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.4")]


